s3:
  enableS3: true
  enableIAM: false
  logDirectory: s3a://spark-hs/spark-hs
  # accessKeyName is an AWS access key ID. Omit for IAM role-based or provider-based authentication.
  secret: s3-secret
  accessKeyName: S3_ACCESS_KEY
  # secretKey is AWS secret key. Omit for IAM role-based or provider-based authentication.
  secretKeyName: S3_SECRET_KEY
  endpoint: https://hb.bizmrg.com

gcs:
  enableGCS: false
  logDirectory: gs://spark-hs/

pvc:
  enablePVC: false

nfs:
  enableExampleNFS: false

service:
  type: LoadBalancer
